# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announce_text', models.TextField(blank=True, max_length=512, null=True)),
                ('full_text', models.TextField(blank=True, max_length=4098)),
            ],
            options={
                'ordering': ['created_at'],
                'verbose_name_plural': 'Articles',
                'verbose_name': 'Article',
            },
        ),
    ]
