# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170416_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='content_type',
            field=models.SmallIntegerField(choices=[(0, 'статья'), (1, 'новость')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.BooleanField(help_text='false - dislike; true - like'),
        ),
    ]
